In [ ]:
Basic operations of a Numpy:

In [2]:
import numpy as np

In [3]:
a = np.array([10,10,10])

In [4]:
b = np.array([5,5,5])

In [5]:
a+b

array([15, 15, 15])

In [6]:
a-b

array([5, 5, 5])

In [7]:
a/b

array([2., 2., 2.])

In [8]:
a%3

array([1, 1, 1], dtype=int32)

In [ ]:
understanding dot function or dot method.

In [11]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print('A:\n',A)
print('B:\n',B)

A:
 [[1 1]
 [0 1]]
B:
 [[2 0]
 [3 4]]


In [12]:
A*B #element wise multiplication

array([[2, 0],
       [0, 4]])

In [13]:
A.dot(B) # 1*2+1*3. 1*0+1*4. 0*2+1*3. 0*0+1*4 (row*column)

array([[5, 4],
       [3, 4]])

In [ ]:
unary operators

In [14]:
ages = np.array([12, 15, 18, 20])

In [16]:
ages.sum()

65

In [17]:
ages.max()

20

In [18]:
ages.min()

12

In [21]:
numbers = np.arange(12).reshape(3,4)

numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
rows n colimn wise operations:

In [ ]:
axis o---->represents cols
axis 1---->represents rows

In [22]:
numbers.sum(axis=0) #sum up columns

array([12, 15, 18, 21])

In [23]:
numbers.sum(axis=1) #sum up rows

array([ 6, 22, 38])

In [ ]:
universal functions of numpy:

In [25]:
test_scores = np.array([32.32, 45.36, 21.52, 44.32, 13.75])

In [26]:
print('mean test scores of students:')
print(np.mean(test_scores))

mean test scores of students:
31.454
